# NumPy - Numerical Python

`NumPy` – **Num**erical **Py**thon neizostavni je paket za kompleksne matematičke proračune u Pythonu. Nudi jako puno matematičkih funkcija, generator je nasumičnih brojeva, podrška je za proračune vezane uz linearnu algebru, Fourierove transformacije..

`Numpy` i ostale alate razvijene oko njega možemo gledati kao `.py` varijantu popularnog `Matlab-a` koji koristi se za tehničke proračune, razvoj modela i algoritama i sl.

Kako su povezani Python i alat Matlab? Matlab je snažan alat, ali u njemu nije tako jednostavno pisati kôd. Bilo bi odlično kada bismo imali snagu Matlaba, a jednostavnost Pythona. Tako dolazimo do seta library-a (skupina klasa i metoda određenih funkcionalnosti) koji koriste Python i koji su alternativa Matlabu.

- `Scipy` (**Sci**entific **Py**thon) - razvijen na temeljima `NumPy biblioteke` i nudi veliki izbor gotovih algoritama za razne znanstvene proračune
- `pandas` - služi za obradu podataka u obliku tablice
- `matplotlib` - služi za vizualizaciju podataka

In [1]:
import numpy as np

In [2]:
obicna_lista = [1, 2, 3, 4, 5]
numpy_lista = np.array(obicna_lista)

Koje su razlike između "obične" `python` liste i `numpy` liste?

In [3]:
print(obicna_lista)
print(type(obicna_lista))

[1, 2, 3, 4, 5]
<class 'list'>


In [4]:
print(numpy_lista)
print(type(numpy_lista))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
print(obicna_lista * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [6]:
print(numpy_lista * 2)

[ 2  4  6  8 10]


In [7]:
obicna_lista_duplo = [x * 2 for x in obicna_lista]

In [8]:
obicna_lista_duplo

[2, 4, 6, 8, 10]

In [9]:
print(np.multiply(obicna_lista, 3))

[ 3  6  9 12 15]


In [10]:
print(len(obicna_lista))

5


In [11]:
print(len(numpy_lista))

5


In [12]:
numpy_lista.size

5

In [13]:
obicna_matrica = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [14]:
print(type(obicna_matrica))
print(obicna_matrica)

<class 'list'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [15]:
numpy_matrica = np.array(obicna_matrica)

In [16]:
print(type(numpy_matrica))
print(numpy_matrica)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(len(obicna_matrica))

3


In [18]:
print(len(numpy_matrica))

3


In [19]:
numpy_matrica.size

9

Kako pristupamo elementima u `numpy` listi? 

In [20]:
print(obicna_lista[0])

1


In [21]:
print(numpy_lista[0])

1


In [22]:
print(obicna_matrica[1][1])

5


In [23]:
print(numpy_matrica[1][1])

5


In [24]:
print(numpy_matrica[1, 1])

5


In [25]:
print(numpy_matrica[0, 1])

2


In [26]:
print(obicna_matrica[0, 1])

TypeError: list indices must be integers or slices, not tuple

In [27]:
obicna_3d_lista = [
    [
        [1, 1],
        [2, 2]
    ],
    [
        [3, 3],
        [4, 4]
    ]
]

In [28]:
print(len(obicna_3d_lista))

2


In [29]:
print(obicna_3d_lista[1][1][0])

4


In [30]:
numpy_3d_lista = np.array(obicna_3d_lista)

In [31]:
numpy_3d_lista.size

8

In [32]:
print(numpy_3d_lista[1][1][0])
print(numpy_3d_lista[1, 1, 0])

4
4


In [33]:
print(obicna_3d_lista)

[[[1, 1], [2, 2]], [[3, 3], [4, 4]]]


In [34]:
print(numpy_3d_lista)

[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]


In [35]:
numpy_3d_lista.ndim

3

In [36]:
numpy_matrica.ndim

2

In [37]:
numpy_lista.ndim

1

In [38]:
numpy_0d_lista = np.array(1)

In [40]:
print(type(numpy_0d_lista))

<class 'numpy.ndarray'>


In [41]:
numpy_0d_lista.ndim

0

In [42]:
numpy_0d_lista.size

1

In [44]:
py_lista_2 = [
    [1, 2, 3],
    [4, 5],
    [6]
]
np_lista_2 = np.array(py_lista_2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## Zadatak
Ispisati broj redaka i stupaca u matrici spremljenoj u varijablama `obicna_matrica` i `numpy_matrica`.

In [45]:
print(len(obicna_matrica), len(obicna_matrica[0]))

3 3


In [46]:
print(len(numpy_matrica), len(numpy_matrica[0]))

3 3


In [47]:
numpy_matrica.shape

(3, 3)

In [48]:
stringovi = ["Prvi", "Drugi", "Treci"]
np_stringovi = np.array(stringovi)

In [49]:
np_stringovi

array(['Prvi', 'Drugi', 'Treci'], dtype='<U5')

In [50]:
numpy_matrica

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
numpy_matrica.dtype

dtype('int32')

In [52]:
np_stringovi.dtype

dtype('<U5')

In [53]:
print(stringovi * 2)
print(np_stringovi * 2)

['Prvi', 'Drugi', 'Treci', 'Prvi', 'Drugi', 'Treci']


UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U5'), dtype('int32')) -> None

In [54]:
numpy_lista

array([1, 2, 3, 4, 5])

In [55]:
numpy_lista.dtype  # ispisuje tip podataka koji su spremljeni u ovoj numpy listi

dtype('int32')

In [56]:
numpy_lista.nbytes

20

In [57]:
numpy_lista_2 = np.array(obicna_lista, dtype=np.int64)

In [58]:
numpy_lista_2

array([1, 2, 3, 4, 5], dtype=int64)

In [59]:
numpy_lista_2.nbytes

40

In [61]:
numpy_lista_float = np.array(obicna_lista, dtype=np.float32)

In [62]:
numpy_lista_float

array([1., 2., 3., 4., 5.], dtype=float32)

In [66]:
numpy_lista_float.nbytes  # koliko memorije zauzimaju svi elementi

20

In [65]:
numpy_lista_float.itemsize  # koliko memorije zauzima svaki pojedini element

4

In [67]:
mijesana_lista = [1, 2.5, True, "bla", None]

In [68]:
np_mijesana_lista = np.array(mijesana_lista)

In [69]:
np_mijesana_lista

array([1, 2.5, True, 'bla', None], dtype=object)

In [71]:
numpy_test_lista = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=np.float32)

In [72]:
numpy_test_lista

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [73]:
numpy_test_lista.ndim

1

In [77]:
np_2d_test_lista = numpy_test_lista.reshape(3, 3)

In [75]:
np_2d_test_lista

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

## Zadatak

Definirati listu s barem 10 cijelih brojeva.

Na temelju početne liste kreirati dvije nove i to na način da u jednoj budu svi parni, a u drugoj svi neparni brojevi iz originalne liste.

In [78]:
originalna_lista = [6, 3, 1, 10, 5, 7, 9, 2, 2, 2]

lista_parnih = [x for x in originalna_lista if x % 2 == 0]
lista_neparnih = [x for x in originalna_lista if x % 2 != 0]

In [79]:
lista_parnih

[6, 10, 2, 2, 2]

In [80]:
lista_neparnih

[3, 1, 5, 7, 9]

In [91]:
np_originalna = np.array(originalna_lista)

np_lista_parnih = np_originalna[np_originalna % 2 == 0]

# where vraća indekse elemenata koji zadovoljavaju određeni uvjet
# np_indeksi_parnih = np_originalna.where(np_originalna % 2 == 0)

np_lista_neparnih = np_originalna[np_originalna % 2 != 0]


print(np_lista_parnih)
print(np_lista_neparnih)

## Zadatak

Kreirati "praznu" 2d matricu proizvoljnih dimenzija. "Prazno" u ovom slučaju znači da je cijela matrica popunjena nulama.

In [92]:
matrica_nula = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
]

In [93]:
matrica_nula_2 = []

for i in range(3):
    unutarnja = []
    for j in range(3):
        unutarnja.append(0)
    matrica_nula_2.append(unutarnja)

print(matrica_nula_2)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [96]:
np_matrica_nula = np.zeros((3, 3), dtype=np.int32)

In [97]:
np_matrica_nula

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [98]:
np_matrica_jedinica = np.ones((3, 3), dtype=np.int32)

In [99]:
np_matrica_jedinica

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [100]:
np_matrica_dvojki = np_matrica_jedinica * 2

In [101]:
np_matrica_dvojki

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [102]:
np_matrica_pi = np.full((4, 4), 3.14)

In [103]:
np_matrica_pi

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

# Generator brojeva u numpy-u

In [3]:
raspon = np.arange(5, 15)
print(raspon)
print(type(raspon))

[ 5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


In [4]:
raspon_svaki_treci = np.arange(5, 15, 3)
print(raspon_svaki_treci)

[ 5  8 11 14]


In [5]:
np.linspace(5, 15, 3)

array([ 5., 10., 15.])

In [6]:
np.linspace(5, 15, 4)

array([ 5.        ,  8.33333333, 11.66666667, 15.        ])

In [7]:
np.linspace(5, 15, 5)

array([ 5. ,  7.5, 10. , 12.5, 15. ])

In [8]:
np.linspace(2, 8, 2)

array([2., 8.])

In [9]:
np.linspace(2, 8, 3)

array([2., 5., 8.])

In [10]:
np.linspace(2, 8, 4)

array([2., 4., 6., 8.])

## Generiranje nasumičnih brojeva

In [28]:
import random as rd

rnd_py = rd.randint(0, 100)
print(rnd_py)

48


In [25]:
rnd_np = np.random.randint(0, 100)
print(rnd_np)

26


In [32]:
rnd_np_2 = np.random.randint(0, 101, 10)
print(rnd_np_2)

[82 38 20 19  2 17 45 77 87 22]


### Zadatak

Napisati program koji generira nasumične brojeve od 1 do 100. Brojeve je potrebno generirati dok god se svaki broj ne generira barem jednom. Na kraju ispisati koliko je puta svaki broj bio generiran.

#### Rješenje bez `numpy-a`

In [68]:
import time

brojevi = [0] * 50000

start_time = time.time()
while 0 in brojevi:
    broj = rd.randint(1, 50000)
    brojevi[broj - 1] += 1
end_time = time.time()
print(f"Ukupno je generirano {sum(brojevi)} brojeva u {end_time - start_time} sekundi.")

Ukupno je generirano 511831 brojeva u 11.626967430114746 sekundi.


#### Rješenje koristeći `numpy`

In [71]:
brojevi_np = np.zeros(100000, dtype=np.int32)
numbers_generated = set()
total_count = 0

start_time = time.time()

while len(numbers_generated) < 100000:
    num = np.random.randint(1, 100001)
    brojevi_np[num-1] += 1
    numbers_generated.add(num)
end_time = time.time()

print(f"Ukupno je generirano {np.sum(brojevi_np)} brojeva u {end_time - start_time} sekundi.")

Ukupno je generirano 1414633 brojeva u 3.4197845458984375 sekundi.


In [83]:
random_float = np.random.rand()  # 1 broj između 0 i 1
print(random_float)
random_float_2 = np.random.rand(2, 5)  # 2 liste po 5 brojevi, svaki između 0 i 1
print(random_float_2)

0.6317795087753549
[[0.44965035 0.17579534 0.02730253 0.39339248 0.3319254 ]
 [0.82055333 0.54506473 0.47515765 0.444814   0.04411418]]


In [86]:
random_matrica = np.random.randint(1, 11, (3, 3))
print(random_matrica)

[[9 1 6]
 [3 7 9]
 [7 2 5]]


### Odabir nasumičnih elemenata iz skupa (liste)

In [93]:
np_lista = np.array([1, 10, 100, 1000])
np_random = np.random.choice(np_lista)

print(np_random)

np_random_podskup = np.random.choice(np_lista, size=(10,))
print(np_random_podskup)

np_random_matrica = np.random.choice(np_lista, size=(2, 3))
print(np_random_matrica)

1
[   1   10 1000 1000 1000   10 1000    1    1   10]
[[100  10   1]
 [  1  10 100]]


In [104]:
np_lista_1_5 = np.array([1, 2, 3, 4, 5])

rnd_10 = np.random.choice(np_lista_1_5, p=[0.0, 0.5, 0.3, 0.1, 0.1], size=10)
print(rnd_10)

[2 3 2 2 3 4 2 2 2 5]


## Manipulacija `numpy` nizova

In [108]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
l1_np = np.array(l1)
l2_np = np.array(l2)

print(l1 + l2)
print(l1_np + l2_np)
print(np.concatenate((l1_np, l2_np, np.array([7, 8, 9]))))

[1, 2, 3, 4, 5, 6]
[5 7 9]
[1 2 3 4 5 6 7 8 9]


In [118]:
l3_np = np.array([l1, l2])
#print(l3_np)
print(np.concatenate((l3_np, l3_np)))  # axis=0
print("************")
print(np.concatenate((l3_np, l3_np), axis=1))

print(np.vstack((l3_np, l3_np)))
print(np.hstack((l3_np, l3_np)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
************
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


## Matematičke operacija s nizovima

In [139]:
l1_np = np.array([1, 2, 3])
l2_np = np.array([10, 9, 8])

print("Zbrajanje: ")
print(l1_np + l2_np)
print(np.add(l1_np, l2_np))

print("Oduzimanje: ")
print(l1_np - l2_np)
print(np.subtract(l1_np, l2_np))

print("Množenje: ")
print(l1_np * l2_np)
print(np.multiply(l1_np, l2_np))

print("Dijeljenje: ")
print(l1_np / l2_np)
print(np.divide(l1_np, l2_np))

print("Potenciranje: ")
print(l2_np ** l1_np)
print(np.power(l2_np, l1_np))

print("Modulo: ")
print(l2_np % l1_np)
print(np.mod(l2_np, l1_np))
print(np.remainder(l2_np, l1_np))
print(np.divmod(l2_np, l1_np))

print("Apsolutna vrijednost: ")
print(np.absolute(np.array([-2, -1, 0, 1, 2])))  # koristiti ovaj
print(np.abs(np.array([-2, -1, 0, 1, 2])))

print("Zaokruživanje: ")
print(np.around(6.219234234, 2))
print(np.around(np.array([4.32323, 5.99, 5.129, 3.1631213124245346]), 2))
print(np.floor(np.array([4.32323, 5.99, 5.129, 3.1631213124245346])))
print(np.ceil(np.array([4.32323, 5.99, 5.129, 3.1631213124245346])))

print("Logaritmi: ")
print(np.log2(10))  # logaritam po bazi 2 od broja 10
print(np.log10(10))  # logaritam po bazi 10 od broja 10
print(np.log(10))  # logaritam po bazi 10 od broja 10

print("Sumiranje: ")
print(np.sum(np.array([1, 2, 3])))
print(np.sum([np.array([1, 2, 3]), np.array([4, 5, 6])]))

print("Najmanji zajednički višekratnik: ")
print(np.lcm(4, 6))

print("Najveći zajednički djelitelj: ")
print(np.gcd(9, 6))

Zbrajanje: 
[11 11 11]
[11 11 11]
Oduzimanje: 
[-9 -7 -5]
[-9 -7 -5]
Množenje: 
[10 18 24]
[10 18 24]
Dijeljenje: 
[0.1        0.22222222 0.375     ]
[0.1        0.22222222 0.375     ]
Potenciranje: 
[ 10  81 512]
[ 10  81 512]
Modulo: 
[0 1 2]
[0 1 2]
[0 1 2]
(array([10,  4,  2]), array([0, 1, 2]))
Apsolutna vrijednost: 
[2 1 0 1 2]
[2 1 0 1 2]
Zaokruživanje: 
6.22
[4.32 5.99 5.13 3.16]
[4. 5. 5. 3.]
[5. 6. 6. 4.]
Logaritmi: 
3.321928094887362
1.0
2.302585092994046
Sumiranje: 
6
21
Najmanji zajednički višekratnik: 
12
3


## Statističke operacije u `numpy-u`

Generirati niz od 10 nasumičnih brojeva iz intervala od 1 do 10.

In [151]:
np_rnd = np.random.randint(0, 11, size=10)
print(np_rnd)

[ 3  3  0  6  3  9  0  6  8 10]


In [153]:
print("Prosjek: ")
print(np.mean(np_rnd))

print("Medijan: ")
print(np.median(np_rnd))

print("Standardna devijacija: ")
print(np.std(np_rnd))

print("Najmanja vrijednost: ")
print(np.min(np_rnd))

print("Najveća vrijednost: ")
print(np.max(np_rnd))

print(np.all(np_rnd)) # vraća True ako se SVAKI element u nizu evaluira u True
print(np.any(np_rnd))  # vraća True ako se BAREM JEDAN element u nizu evaluira u True

Prosjek: 
4.8
Medijan: 
4.5
Standardna devijacija: 
3.3704599092705436
Najmanja vrijednost: 
0
Najveća vrijednost: 
10
False
True


## Funkcije filtriranja

In [154]:
l1 = np.linspace(-4, 4, 9)
print(l1)

[-4. -3. -2. -1.  0.  1.  2.  3.  4.]


In [156]:
print(np.where(l1 < 0, l1**2, l1**3))

[16.  9.  4.  1.  0.  1.  8. 27. 64.]


In [158]:
print(np.select([l1 < -1, l1 <= 2, l1 >= 2], [l1 + 1, l1 + 2, l1 + 3]))

[-3. -2. -1.  1.  2.  3.  4.  6.  7.]


In [169]:
l2 = np.random.randint(1, 11, size=10)
print(l2)
print(np.unique(l2))
print(np.sort(l2))

[4 2 5 6 3 3 3 7 6 1]
[1 2 3 4 5 6 7]
[1 2 3 3 3 4 5 6 6 7]


### Rješavanja jednadžbi

In [174]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

# x + 2y = 5
# 3x + 4y = 6
result = np.linalg.solve(a, b)
print(result)


a = np.array([[1, 2, 4], [3, 4, -3], [-2, -5, 1]])
b = np.array([7, 10, -5])
result = np.linalg.solve(a, b)
print(result)

[-4.   4.5]
[ 5.66666667 -1.09090909  0.87878788]


# Zadatak

### Priča o najpoznatijoj matrici na svijetu - šahovskoj ploči

**Šah**

Najpoznatija matrica je ploča za jednu od najstarijih igara - šah. To je matrica 8x8.
Legenda o tome kako je igra dobila ime šah je jako zanimljiva. Šah (perzijski naziv za vladara) je gledao kako njegove sluge od putujućih trgovaca kupuju namirnice, tkaninu, začine i sl. Tako je ugledao dvojicu trgovaca kako igraju neku čudnu igru. Poslao je slugu da dovede trgovca koji je donio tu igru u njegovo kraljevstvo. Šah (vladar) je zatražio od trgovca da ga nauči igrati. Kada je naučio kako se igra, šah se toliko oduševio igrom da je odlučio bogato nagraditi trgovca. Rekao mu je neka kaže što želi kao nagradu za ovu igru. Trgovac je šahu, nakon što je naveo sve one slatkorječive riječi vladarima, kao što su Vaša visosti i sl., rekao:

*Želim pšenicu. Na prvo polje stavite jedno zrno pšenice. Na drugo dva zrna, na treće četiri, na četvrto dva puta više od prethodnog ... i tako do posljednjeg 64.-og polja.*

Šah se jako uvrijedio jer je očekivao da će trgovac tražiti zlato, drago kamenje, skupe začine pa ga je potjerao u vrt rekavši mu da će svoju vreću pšenice dobiti za ručak. Slugama je naredio neka ga isplate i to da nikada više ne želi vidjeti tog trgovca u njegovom kraljevstvu.

**PITANJE<br>
Koliko je trgovac trebao dobiti pšenice? Napišite program koji će to izračunati.**

In [177]:
lista = [2**i for i in range(0, 64)]
print(sum(lista))

18446744073709551615


In [179]:
broj_zrna_psenica = 0
for i in range(65):
    if i == 0:
        broj_zrna_psenica += 1
    else:
        broj_zrna_psenica *= 2

print(broj_zrna_psenica)

18446744073709551616
