In [1]:
import numpy as np

## Ponavljanje

Bez korištenje `numpy-a`, ispisati tablicu množenja do 10.

In [12]:
def tablica_mnozenja(limit=10):
    for i in range(1, limit + 1):
        for j in range(1, limit + 1):
            rez = i * j
            print(rez, end="\t")
        
        print()
        
tablica_mnozenja()
# tablica_mnozenja(5)
# tablica_mnozenja(16)

1	2	3	4	5	6	7	8	9	10	
2	4	6	8	10	12	14	16	18	20	
3	6	9	12	15	18	21	24	27	30	
4	8	12	16	20	24	28	32	36	40	
5	10	15	20	25	30	35	40	45	50	
6	12	18	24	30	36	42	48	54	60	
7	14	21	28	35	42	49	56	63	70	
8	16	24	32	40	48	56	64	72	80	
9	18	27	36	45	54	63	72	81	90	
10	20	30	40	50	60	70	80	90	100	


Koristeći `numpy`, kreirati niz koji predstavlja tablicu množenja do 10.

In [14]:
#redak = np.array([i for i in range(1, 11)])
redak = np.arange(1, 11)

for n in range(1, 11):
    tabl = redak * n
    print(tabl)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[ 3  6  9 12 15 18 21 24 27 30]
[ 4  8 12 16 20 24 28 32 36 40]
[ 5 10 15 20 25 30 35 40 45 50]
[ 6 12 18 24 30 36 42 48 54 60]
[ 7 14 21 28 35 42 49 56 63 70]
[ 8 16 24 32 40 48 56 64 72 80]
[ 9 18 27 36 45 54 63 72 81 90]
[ 10  20  30  40  50  60  70  80  90 100]


In [17]:
def np_tabl(limit=10):
    tabl2 = np.zeros((limit, limit), dtype=np.int32)
    for i in range(limit):
        for j in range(limit):
            tabl2[i][j] = (i + 1) * (j + 1)
    
    print(tabl2)

np_tabl()
np_tabl(3)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [19]:
def np_tabl2(i, j):
    return (i + 1) * (j + 1)

table = np.fromfunction(np_tabl2, (10, 10), dtype=np.int32)
print(table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [20]:
table = np.fromfunction(np_tabl2, (3, 3), dtype=np.int32)
print(table)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


### Dodatni `fromfunction` primjer

Imamo dva broja koja želimo transformirati tako da drugi broj pomnožimo s brojem 15 i to dodamo prvom broju.
Opisano ponašanje napisati u obliku funkcije i tu funkciju iskoristiti kao ulazni parametar za kreiranje `numpy` niza.

In [22]:
def test_funkcija(x, y):
    return y * 15 + x

np_test = np.fromfunction(test_funkcija, (2, 2), dtype=np.int32)

print(np_test)

[[ 0 15]
 [ 1 16]]


In [24]:
np_test_2 = np.fromfunction(lambda x, y: y * 15 + x, (2, 2), dtype=int)

print(np_test_2)
print(np_test_2.dtype)

[[ 0 15]
 [ 1 16]]
int32


# Zapisivanje u tekstualne datoteke koristeći `numpy`

In [25]:
tablica_mnozenja_do_10 = np.fromfunction(np_tabl2, (10, 10), dtype=np.int32)
print(tablica_mnozenja_do_10)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [35]:
np.savetxt("tablica_mnozenja_do_10.txt", tablica_mnozenja_do_10, fmt="%d")

## Zadatak

U datoteku `tablica_mnozenja.txt` zapišite tablicu množenja od 1 do 10, dodajte zaglavlje u kojem će pisati sljedeći tekst:

**Naziv datoteke: tablica_mnozenja.txt**

**Autor: "Ime Prezime"**  # zamijenite sa svojim imenom i prezimenom
_________________________
"umetni tablicu mnozenja"
__________________________

Nakon tablice množenja zapisati `datum i vrijeme` kreiranje datoteke.

In [38]:
import datetime as dt

In [87]:
header = "Naziv datoteke: tablica_mnozenja.txt\nAutor: Pero Peric\n--------------------------------"
footer = f"---------------------------\nDatum i vrijeme zapisivanja:{dt.datetime.now().strftime('%d.%m.%Y %H:%M:%S')}"
np.savetxt("tablica_mnozenja.txt", tablica_mnozenja_do_10, fmt="%i", header=header, footer=footer)

In [43]:
header_2 = """Naziv datoteke: tablica_mnozenja_2.txt
Autor: Pero Perić
**************************************"""
footer_2 = f"""**************************************
Datum i vrijeme zapisivanja: {dt.datetime.now().strftime('%d.%m.%Y %H:%M:%S')}"""
np.savetxt("tablica_mnozenja_2.txt", tablica_mnozenja_do_10, fmt="%i", header=header_2, footer=footer_2)

# Čitanje iz datoteka koristeći `numpy`

In [106]:
np.loadtxt?

In [114]:
def konverzija(x):
    val = int(x)
    if val < 5:
        return val ** 3
    else:
        return val ** 2

In [115]:
# tablica_mnozenja_datoteka = np.loadtxt("tablica_mnozenja.txt")
# tablica_mnozenja_datoteka = np.loadtxt("tablica_mnozenja.txt", dtype=int)
# tablica_mnozenja_datoteka = np.loadtxt("tablica_mnozenja.txt", dtype=int, skiprows=5)
# tablica_mnozenja_datoteka = np.loadtxt("tablica_mnozenja.txt", dtype=int, usecols=(1, 3))
tablica_mnozenja_datoteka = np.loadtxt(
    "tablica_mnozenja.txt",
    dtype=int,
    converters={
        0: konverzija
    }
)

In [116]:
tablica_mnozenja_datoteka

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  8,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 27,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [ 64,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [ 25,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [ 36,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [ 49,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [ 64,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [ 81,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [100,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [127]:
e_cars_np = np.loadtxt(
    "e-cars.csv",
    delimiter=";",  # vrijednosti su nam odvojene sa ;
    skiprows=1,  # prvi red sadrži nazive stupaca, to preskačemo
    dtype=str,  # imamo stringove i integere pa trebamo sve pretvoriti u str inače imamo grešku
)

In [131]:
print(e_cars_np)

[['2012' 'MITSUBISHI' 'i-MiEV' 'SUBCOMPACT' '49' 'A1' 'B' '16.9' '21.4'
  '18.7' '1.9' '2.4' '2.1' '0' 'n/a' '100' '7']
 ['2012' 'NISSAN' 'LEAF' 'MID-SIZE' '80' 'A1' 'B' '19.3' '23' '21.1'
  '2.2' '2.6' '2.4' '0' 'n/a' '117' '7']
 ['2013' 'FORD' 'FOCUS ELECTRIC' 'COMPACT' '107' 'A1' 'B' '19' '21.1'
  '20' '2.1' '2.4' '2.2' '0' 'n/a' '122' '4']
 ['2013' 'MITSUBISHI' 'i-MiEV' 'SUBCOMPACT' '49' 'A1' 'B' '16.9' '21.4'
  '18.7' '1.9' '2.4' '2.1' '0' 'n/a' '100' '7']
 ['2013' 'NISSAN' 'LEAF' 'MID-SIZE' '80' 'A1' 'B' '19.3' '23' '21.1'
  '2.2' '2.6' '2.4' '0' 'n/a' '117' '7']
 ['2013' 'SMART' 'FORTWO ELECTRIC DRIVE CABRIOLET' 'TWO-SEATER' '35' 'A1'
  'B' '17.2' '22.5' '19.6' '1.9' '2.5' '2.2' '0' 'n/a' '109' '8']
 ['2013' 'SMART' 'FORTWO ELECTRIC DRIVE COUPE' 'TWO-SEATER' '35' 'A1' 'B'
  '17.2' '22.5' '19.6' '1.9' '2.5' '2.2' '0' 'n/a' '109' '8']
 ['2013' 'TESLA' 'MODEL S (40 kWh battery)' 'FULL-SIZE' '270' 'A1' 'B'
  '22.4' '21.9' '22.2' '2.5' '2.5' '2.5' '0' 'n/a' '224' '6']
 ['2013' 'TESLA

### Pomoć za `slice` notaciju

<img src="slike/array-slice.png" alt="Array slice notacija"/>

In [132]:
print(e_cars_np[0])

['2012' 'MITSUBISHI' 'i-MiEV' 'SUBCOMPACT' '49' 'A1' 'B' '16.9' '21.4'
 '18.7' '1.9' '2.4' '2.1' '0' 'n/a' '100' '7']


In [140]:
print(e_cars_np[:, 0])

['2012' '2012' '2013' '2013' '2013' '2013' '2013' '2013' '2013' '2013'
 '2013' '2014' '2014' '2014' '2014' '2014' '2014' '2014' '2014' '2014'
 '2015' '2015' '2015' '2015' '2015' '2015' '2015' '2015' '2015' '2015'
 '2015' '2015' '2015' '2015' '2016' '2016' '2016' '2016' '2016' '2016'
 '2016' '2016' '2016' '2016' '2016' '2016' '2016' '2016' '2016' '2016'
 '2016' '2016' '2016']


Trebali bi svaki stupac koji ne treba biti string na ovaj način dohvatiti, odraditi konverziju podataka što je prilično neefikasno i zamorno. Postoji li bolji način?