### NUMPY 
numpy je pythonov odgovor na matlab
numpy nudi jako puno matematickih funkcija

kada instaliramo NumPy dobijemo:
- Acipy (Scientific Python) - razvijen na temeljima NumPy biblioteke i nudei velik izbor gotovih algoritama uz razne znanstvene proracune
- pandas - sluzi za obradu potadaka iz tablice
- matplotlib - sluzi za vizualizaciju podataka

In [2]:
import numpy as np

obicna_lista = [1, 2, 3, 4, 5]
numpy_lista = np.array(obicna_lista)

print(obicna_lista)
print(type(obicna_lista))

print(numpy_lista)
print(type(numpy_lista))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [110]:
print(obicna_lista * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [114]:
print(numpy_lista * 2)

[ 2  4  6  8 10]


In [115]:
obicna_lista_duplo = [x * 2 for x in obicna_lista]
print(obicna_lista_duplo)

[2, 4, 6, 8, 10]


In [116]:
print(np.multiply(obicna_lista, 3))

[ 3  6  9 12 15]


In [117]:
print(len(obicna_lista))

5


In [118]:
print(len(numpy_lista))

5


## matrice

In [119]:
obicna_matrica = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(obicna_matrica)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [120]:
numpy_matrica = np.array(obicna_matrica)
print(numpy_matrica)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [121]:
print(len(obicna_matrica))

3


In [123]:
print(len(numpy_matrica))

3


In [124]:
numpy_matrica.size

9

### kako pristupamo elemtima u numpy listi 

In [125]:
print(obicna_lista[0])

1


In [126]:
print(numpy_lista[0])

1


In [127]:
print(obicna_matrica[1][1])

5


In [128]:
print(numpy_matrica[1][1])

5


In [129]:
print(numpy_matrica[1, 1])

5


In [130]:
obicna_3d_lista = [
    [
        [1, 1],
        [2, 2]
    ],
    [
        [3, 3],
        [4, 4]
    ],
    
]

In [131]:
print(len(obicna_3d_lista))

2


In [132]:
print(obicna_3d_lista[1][1][0])

4


In [133]:
print(obicna_3d_lista)

[[[1, 1], [2, 2]], [[3, 3], [4, 4]]]


In [134]:
numpy_3d_lista = np.array(obicna_3d_lista)


In [136]:
numpy_3d_lista.ndim

3

In [137]:
numpy_matrica.ndim

2

In [138]:
numpy_lista.ndim

1

In [62]:
numpy_0d_lista = np.array(1)

In [139]:
numpy_0d_lista.ndim

0

In [140]:
numpy_0d_lista.size

1

In [141]:
#py_lista = [
    #[1, 2, 3],
    #[4, 5],
    #[6]
#]

#np_lista = np.array(py_lista)

## Zadatak:

ispisati broj redaka i stupaca u matrici spremljenoj u varijablama obicna_matrica i numpy_matrica

In [142]:
print(len(obicna_matrica), len(obicna_matrica[0]))

3 3


In [143]:
print(len(numpy_matrica), len(numpy_matrica[0]))

3 3


In [144]:
numpy_matrica.shape

(3, 3)

In [145]:
stringovi = ["AA", "BB", "CC"]
np_stringovi = np.array(stringovi)

In [146]:
np_stringovi

array(['AA', 'BB', 'CC'], dtype='<U2')

In [147]:
numpy_matrica.dtype

dtype('int32')

In [148]:
np_stringovi.dtype

dtype('<U2')

In [86]:
print(stringovi * 2)
#print(np_stringovi * 2)

['AA', 'BB', 'CC', 'AA', 'BB', 'CC']


In [87]:
numpy_lista.dtype # ispisuje toip podataka u tom arrayu

dtype('int32')

In [88]:
numpy_lista.nbytes

20

In [89]:
numpy_lista_2 = np.array(obicna_lista, dtype=np.int64)

In [90]:
numpy_lista_2

array([1, 2, 3, 4, 5], dtype=int64)

In [93]:
numpy_lista_2.nbytes

40

In [95]:
numpy_lista_float = np.array(obicna_lista, dtype=np.float32)

In [97]:
numpy_lista_float

array([1., 2., 3., 4., 5.], dtype=float32)

In [98]:
numpy_lista_float.nbytes # koliko memorije zauzimaju svi elementi

20

In [99]:
numpy_lista_float.itemsize # koliko memorije zauzima svaki pojedini element

4

In [100]:
mijesana_lista = [1, 2.5, "bla", None]

In [101]:
numpy_mijesana_lista = np.array(mijesana_lista)

In [103]:
numpy_mijesana_lista #kada je dtype=object, znaci da imamo mix podataka u tom arrayu

array([1, 2.5, 'bla', None], dtype=object)

In [104]:
numpy_test_lista = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=np.float32)

In [105]:
numpy_test_lista.ndim

1

In [106]:
numpy_test_lista.reshape(3, 3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [108]:
#numpy_test_lista.reshape(2, 4) #nope

### ZADATAK 1 :
definirati listu s barem 10 elemenata cijelih brojeva.

na temelju pocetne liste kreirati dvije nove i to na nacin da u jednoj budu svi parni a u drugoj svi neparni brojevi

In [159]:
zadatak_lista = [6, 3, 1, 10, 5, 7, 9, 2, 2, 2]

In [160]:
lista_even = [i for i in zadatak_lista if i % 2 == 0]
lista_odd = [i for i in zadatak_lista if i % 1 == 0]
for i in lista_even:
    print(i)

6
10
2
2
2


 ista stvar s numpy:

In [175]:
np_originalna = np.array(zadatak_lista)
np_indeksi_parnih = np.where(np_originalna % 2 == 0)
np_indeksi_neparnih = np.where(np_originalna % 1 == 0)

In [176]:
print(np_indeksi_parnih)
print(np_indeksi_neparnih)

(array([0, 3, 7, 8, 9], dtype=int64),)
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)


In [177]:
np_originalna = np.array(zadatak_lista)
np_lista_parnih = np_originalna[np_originalna % 2 == 0]
np_lista_neparnih = np_originalna[np_originalna % 2 != 0]

In [178]:
print(np_lista_parnih)
print(np_lista_neparnih)

[ 6 10  2  2  2]
[3 1 5 7 9]


### ZADATAK 2 :
kreirati "praznu" 2d matricu proizvoljnih dimenzija. "prazno"u ovom slucaju znaci da je cijela matrica popunjena nulama.

In [ ]:
prazna_2d_matrica = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
]

In [180]:
prazna_2d_matrica_2 = []
for i in range(3):
    unutarnja=[]
    for i in range(3):
        unutarnja.append(0)
    prazna_2d_matrica_2.append(unutarnja)
print(prazna_2d_matrica_2)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


NUMPY PRIMJER:

In [184]:
np_prazna_2d_matrica = np.zeros((9,9), dtype=np.int32)

In [186]:
print(np_prazna_2d_matrica)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [187]:
np_matrica_dvojke = np.ones((9,9), dtype=np.int32)
print(np_matrica_dvojke)

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


In [193]:
np_matrica_pi = np.full((9,9), 3.14)
print(np_matrica_pi)

[[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]]


### ZADATAK 3 :
kreirati listu koja pocinje od 5, ima 5 elemenata i to na nacin da je svaki jednak vrijednosti prethodnog uvecano za 3

    "5, 8, 11, 14, 17"

In [198]:
lista_svaki_treci = range(5, 10)

In [199]:
print(lista_svaki_treci)

range(5, 10)


In [200]:
for broj in lista_svaki_treci:
    print(broj)

5
6
7
8
9


In [ ]:
# NUMPY NACIN
np_svaki_treci = np.linalg

02.03.2022

 ### NUMPY _ GENERAOTOR NASUMICNIH BROJEVA

In [7]:
import random as rd

#Generator brojeva u numpy-u¶
raspon = np.arange(5, 15)
print(raspon)

print(type(raspon))
 

raspon_svaki_treci = np.arange(5, 15, 3)
print(raspon_svaki_treci)
 

np.linspace(5, 15, 3)
 



#Generiranje nausmičnih brojeva

 

import random as rd
rnd_py = rd.randint(0, 100)
print(rnd_py)

rnd_np = np.random.randint(0, 100)
print(rnd_np)
 
rnd_np_2 = np.random.randint(0, 100, 10)
print(rnd_np_2)

[ 5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
[ 5  8 11 14]
41
64
[19 43 26 36 73 38 81 61 69 58]


### Zadatak

napisati program koji generira nasumicne brojeve od 1 do 100. broijeve je potrebno generirati dok god se svaki broj ne generira barem jednom. na kraju ispisati koliko je puta svaki broj bio generiran

In [47]:
# rjesenje bez numpy-a

import time

brojevi = [0] * 10000

start_time = time.time()
while 0 in brojevi: 
    broj = rd.randint(1, 10000)
    brojevi[broj - 1] += 1
end_time = time.time()
print(f"Ukupno je generirano {sum(brojevi)} brojeva u {end_time - start_time} sekundi.")   
for idx, broj in enumerate(brojevi):
    print(f"Broj {idx + 1} se pojavio {broj} puta.")

Ukupno je generirano 88204 brojeva u 0.9129750728607178 sekundi.
Broj 1 se pojavio 10 puta.
Broj 2 se pojavio 8 puta.
Broj 3 se pojavio 7 puta.
Broj 4 se pojavio 10 puta.
Broj 5 se pojavio 9 puta.
Broj 6 se pojavio 12 puta.
Broj 7 se pojavio 5 puta.
Broj 8 se pojavio 11 puta.
Broj 9 se pojavio 12 puta.
Broj 10 se pojavio 9 puta.
Broj 11 se pojavio 8 puta.
Broj 12 se pojavio 7 puta.
Broj 13 se pojavio 11 puta.
Broj 14 se pojavio 6 puta.
Broj 15 se pojavio 8 puta.
Broj 16 se pojavio 11 puta.
Broj 17 se pojavio 9 puta.
Broj 18 se pojavio 9 puta.
Broj 19 se pojavio 8 puta.
Broj 20 se pojavio 12 puta.
Broj 21 se pojavio 6 puta.
Broj 22 se pojavio 9 puta.
Broj 23 se pojavio 6 puta.
Broj 24 se pojavio 8 puta.
Broj 25 se pojavio 8 puta.
Broj 26 se pojavio 6 puta.
Broj 27 se pojavio 8 puta.
Broj 28 se pojavio 11 puta.
Broj 29 se pojavio 11 puta.
Broj 30 se pojavio 12 puta.
Broj 31 se pojavio 10 puta.
Broj 32 se pojavio 8 puta.
Broj 33 se pojavio 10 puta.
Broj 34 se pojavio 5 puta.
Broj 35 se po

In [48]:
# rjesenje s numpy-em

brojevi_np = np.zeros(10000, dtype=np.int32)
numbers_generated = set()
total_count = 0

start_time = time.time()

while len(numbers_generated) < 10000:
    num = np.random.randint(1, 10001)
    brojevi_np[num-1] += 1
    numbers_generated.add(num)
    
end_time = time.time()
print(f"Ukupno je generirano {np.sum(brojevi_np)} brojeva u {end_time - start_time} sekundi.")

Ukupno je generirano 110862 brojeva u 0.2826192378997803 sekundi.


In [55]:
random_matrica = np.random.randint(1, 11, (3, 3))
print(random_matrica)

[[10  8 10]
 [ 4  8  5]
 [ 8  8  9]]


In [69]:
import secrets

foo = ['aa', 'bb', 'cc', 'dd', 'ee', 'ff', 'gg', 'hh', 'ii', 'jj', 'kk', 'll',]
print(secrets.choice(foo))

hh


### odabir nasumicnih elemenata iz skupa (liste)

In [63]:
np_lista = np.array([1, 10, 100, 1000])
np_random = np.random.choice(np_lista)

print(np_random)
np_random_podskup = np.random.choice(np_lista, size=(3,))
print(np_random_podskup)

100
[1000  100    1]


In [70]:
np_lista_1_5 = np.array([1, 2, 3, 4, 5])
rnd_10 = np.random.choice(np_lista_1_5, p=[0.0, 0.5, 0.1, 0.3, 0.1] size=10)
print(rnd_10)

# p=[0.0, 0.5, 0.1, 0.3, 0.1]  - ovdje namjestamo koje vjerovatnosti imaju brojevi

[1 5 3 3 4 2 3 2 3 4]
